yucca_in_situ_updater_form:
    path:  /in_situ_updater/{form_name}
    defaults:
        _controller: YuccaInSituUpdaterBundle:Form:index

yucca_in_situ_updater_delete:
    path:  /in_situ_updater/delete/{form_name}
    defaults:
        _controller: YuccaInSituUpdaterBundle:Delete:index
