<?php
namespace Yucca\InSituUpdaterBundle\Event;

use Symfony\Component\EventDispatcher\Event;
use Yucca\InSituUpdaterBundle\Form\AutoGeneratedFormType;

/**
 * Class FormPreCreationEvent
 *
 * @package Yucca\InSituUpdaterBundle\Event
 */
class FormPreCreationEvent extends Event
{
    protected $formType;
    protected $configuration;
    protected $models;

    /**
     * @param AutoGeneratedFormType $formType
     * @param array                 $configuration
     */
    public function __construct(AutoGeneratedFormType $formType, $configuration, $models)
    {
        $this->formType = $formType;
        $this->configuration = $configuration;
        $this->models = $models;
    }

    /**
     * @return AutoGeneratedFormType
     */
    public function getFormType()
    {
        return $this->formType;
    }

    /**
     * @return mixed
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * @return mixed
     */
    public function getModels()
    {
        return $this->models;
    }
}
